"""
Generate XYZ map tiles for FLOOD EXTENT (FloodOut) from existing surge COGs.

Reuses the EPSG:3857 COGs already generated by generate_surge_tiles.py.
Instead of depth-graduated coloring, renders binary flood extent:
  - Flooded areas: solid cyan-blue fill with crisp boundary
  - Not flooded: fully transparent

This gives the SAME performance as depth tiles (pre-rendered XYZ PNGs)
with a distinct visual style for "extent only" toggle.

Output: assets/tiles/surge_extent/{scenario}/{z}/{x}/{y}.png
"""

import os
import sys
import math
import argparse
import time
from pathlib import Path

try:
    import rasterio
    from rasterio.windows import from_bounds as window_from_bounds
    from rasterio.enums import Resampling
    import numpy as np
    from PIL import Image
except ImportError as e:
    print(f"Missing dependency: {e}")
    sys.exit(1)

os.environ['CHECK_DISK_FREE_SPACE'] = 'FALSE'

# ─── Configuration ───────────────────────────────────────────────────────────

TILE_SIZE = 256

# Beautiful extent color — ocean cyan-blue (distinct from red depth tiles)
EXTENT_COLOR = (6, 147, 227)     # Vivid water blue
EXTENT_ALPHA = 160               # Solid but not fully opaque (0-255)
BORDER_COLOR = (3, 105, 161)     # Slightly darker for edge emphasis
BORDER_ALPHA = 210

MIN_ZOOM = 10
MAX_ZOOM = 15

# Web Mercator constants
ORIGIN_SHIFT = 2 * math.pi * 6378137 / 2.0

# Scenarios — reuse the COGs from generate_surge_tiles.py
SCENARIOS = [
    '20yr_2020', '20yr_2050', '20yr_2100', '20yr_2150',
    '100yr_2020', '100yr_2050', '100yr_2100', '100yr_2150',
]


# ─── XYZ Tile Math (EPSG:3857) ──────────────────────────────────────────────

def tile_bounds_3857(x, y, z):
    n = 2 ** z
    tile_size_m = 2 * ORIGIN_SHIFT / n
    min_x = -ORIGIN_SHIFT + x * tile_size_m
    max_x = min_x + tile_size_m
    max_y = ORIGIN_SHIFT - y * tile_size_m
    min_y = max_y - tile_size_m
    return (min_x, min_y, max_x, max_y)


def get_tiles_for_bounds(bounds_3857, zoom):
    min_x, min_y, max_x, max_y = bounds_3857
    n = 2 ** zoom
    tile_size_m = 2 * ORIGIN_SHIFT / n
    min_x = max(min_x, -ORIGIN_SHIFT)
    max_x = min(max_x, ORIGIN_SHIFT)
    min_y = max(min_y, -ORIGIN_SHIFT)
    max_y = min(max_y, ORIGIN_SHIFT)
    x_min = int(math.floor((min_x + ORIGIN_SHIFT) / tile_size_m))
    x_max = int(math.floor((max_x + ORIGIN_SHIFT) / tile_size_m))
    y_min = int(math.floor((ORIGIN_SHIFT - max_y) / tile_size_m))
    y_max = int(math.floor((ORIGIN_SHIFT - min_y) / tile_size_m))
    x_min = max(0, x_min)
    x_max = min(n - 1, x_max)
    y_min = max(0, y_min)
    y_max = min(n - 1, y_max)
    tiles = []
    for ty in range(y_min, y_max + 1):
        for tx in range(x_min, x_max + 1):
            tiles.append((tx, ty, zoom))
    return tiles


# ─── Tile Generation ─────────────────────────────────────────────────────────

def generate_extent_tile(src, tile_x, tile_y, zoom, output_dir, scenario_key):
    """Generate a single binary extent XYZ tile PNG."""
    bounds = tile_bounds_3857(tile_x, tile_y, zoom)

    rb = src.bounds
    if bounds[0] >= rb.right or bounds[2] <= rb.left or \
       bounds[1] >= rb.top or bounds[3] <= rb.bottom:
        return False

    try:
        window = window_from_bounds(
            bounds[0], bounds[1], bounds[2], bounds[3],
            transform=src.transform
        )
        data = src.read(
            1,
            window=window,
            out_shape=(TILE_SIZE, TILE_SIZE),
            resampling=Resampling.nearest,
            boundless=True,
            fill_value=0
        )
    except Exception:
        return False

    # Binary mask: valid flood data (same check as depth tiles)
    nodata = src.nodata
    if nodata is not None:
        mask = (data != 0) & (data != nodata) & (~np.isnan(data)) & (data < 1e30)
    else:
        mask = (data != 0) & (~np.isnan(data)) & (data < 1e30)

    if not mask.any():
        return False

    # Create RGBA tile — solid extent fill with edge enhancement
    rgba = np.zeros((TILE_SIZE, TILE_SIZE, 4), dtype=np.uint8)

    # Fill interior
    rgba[mask, 0] = EXTENT_COLOR[0]
    rgba[mask, 1] = EXTENT_COLOR[1]
    rgba[mask, 2] = EXTENT_COLOR[2]
    rgba[mask, 3] = EXTENT_ALPHA

    # Edge detection for crisp boundary — find pixels adjacent to non-flood
    # Shift mask in 4 directions; boundary = flood pixel with ≥1 non-flood neighbor
    pad_mask = np.pad(mask, 1, mode='constant', constant_values=False)
    edges = mask & (
        ~pad_mask[:-2, 1:-1] |  # top neighbor not flooded
        ~pad_mask[2:, 1:-1]  |  # bottom
        ~pad_mask[1:-1, :-2] |  # left
        ~pad_mask[1:-1, 2:]     # right
    )

    # Darken edges for crisp boundary look
    rgba[edges, 0] = BORDER_COLOR[0]
    rgba[edges, 1] = BORDER_COLOR[1]
    rgba[edges, 2] = BORDER_COLOR[2]
    rgba[edges, 3] = BORDER_ALPHA

    # Save as PNG
    tile_dir = os.path.join(output_dir, scenario_key, str(zoom), str(tile_x))
    os.makedirs(tile_dir, exist_ok=True)
    tile_path = os.path.join(tile_dir, f"{tile_y}.png")

    img = Image.fromarray(rgba, 'RGBA')
    img.save(tile_path, 'PNG', optimize=True)
    return True


def process_scenario(scenario_key, cog_path, output_dir, min_zoom, max_zoom):
    print(f"  Generating extent tiles for {scenario_key}...")

    with rasterio.open(cog_path) as src:
        if src.crs and src.crs.to_epsg() != 3857:
            print(f"    WARNING: CRS is {src.crs}, expected EPSG:3857. Skipping.")
            return 0

        bounds_3857 = (src.bounds.left, src.bounds.bottom,
                       src.bounds.right, src.bounds.top)
        total_tiles = 0

        for zoom in range(min_zoom, max_zoom + 1):
            tiles = get_tiles_for_bounds(bounds_3857, zoom)
            zoom_count = 0
            for tx, ty, z in tiles:
                if generate_extent_tile(src, tx, ty, z, output_dir, scenario_key):
                    zoom_count += 1
            total_tiles += zoom_count
            print(f"    z{zoom}: {zoom_count} tiles")

        print(f"    → {total_tiles} tiles (z{min_zoom}–z{max_zoom})")
        return total_tiles


def main():
    parser = argparse.ArgumentParser(
        description='Generate XYZ extent tiles from existing surge COGs')
    parser.add_argument('--scenario', type=str, default=None)
    parser.add_argument('--zoom', nargs=2, type=int, default=[MIN_ZOOM, MAX_ZOOM])
    args = parser.parse_args()

    min_zoom, max_zoom = args.zoom
    base_dir = os.path.dirname(os.path.abspath(__file__))
    cog_dir = os.path.join(base_dir, 'assets', 'cog_3857', 'surge')
    output_dir = os.path.join(base_dir, 'assets', 'tiles', 'surge_extent')
    os.makedirs(output_dir, exist_ok=True)

    scenarios = [args.scenario] if args.scenario else SCENARIOS

    grand_total = 0
    start_time = time.time()

    print(f"\n{'='*60}")
    print(f"  FLOOD EXTENT TILE GENERATION")
    print(f"  Reusing existing surge COGs (EPSG:3857)")
    print(f"  Scenarios: {len(scenarios)} | Zoom: z{min_zoom}–z{max_zoom}")
    print(f"  Color: Cyan-blue solid fill with crisp edge borders")
    print(f"{'='*60}")

    for key in scenarios:
        cog_path = os.path.join(cog_dir, f"surge_{key}.tif")
        if not os.path.exists(cog_path):
            print(f"  SKIP: COG not found for {key}")
            print(f"         Run generate_surge_tiles.py first!")
            continue

        count = process_scenario(key, cog_path, output_dir, min_zoom, max_zoom)
        grand_total += count

    elapsed = time.time() - start_time
    print(f"\n{'='*60}")
    print(f"DONE — {grand_total} extent tiles in {elapsed:.1f}s")
    print(f"Tiles: {output_dir}")
    print(f"\nTile URL pattern for OpenLayers:")
    print(f"  assets/tiles/surge_extent/{{scenario_key}}/{{z}}/{{x}}/{{y}}.png")
    print(f"{'='*60}")


if __name__ == '__main__':
    main()
